### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kleenkanteen** [goksan/statusnook#4]
Am curious, why create this when other open source solutions exist like https://github.com/louislam/uptime-kuma?

**Comment by goksan** [comment]
Hi @kleenkanteen 

Thanks for the question!

While there are other open source solutions available, I decided to create Statusnook to tailor it to my needs and tastes. I haven't personally deployed any alternative open source solutions, so I can't offer any direct experiences or comparisons.

I've been enjoying building Statusnook, and I've received positive feedback from others since sharing it more widely.

Let me know if you have a question about a specific feature.

**Comment by kleenkanteen** [comment]
I see, thanks for the answer
